// Automatically generated by flapigen
package com.exogress;


public final class Instance {

    public Instance(String access_key_id, String secret_access_key, String account, String project, boolean watch_config) throws Exception {
        mNativeObj = init(access_key_id, secret_access_key, account, project, watch_config);
    }
    private static native long init(String access_key_id, String secret_access_key, String account, String project, boolean watch_config) throws Exception;

    public final void spawn() throws Exception {
        do_spawn(mNativeObj);
    }
    private static native void do_spawn(long self) throws Exception;

    public final void stop() throws Exception {
        do_stop(mNativeObj);
    }
    private static native void do_stop(long self) throws Exception;

    public final void reload() throws Exception {
        do_reload(mNativeObj);
    }
    private static native void do_reload(long self) throws Exception;

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ Instance(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;

     static {
         try {
             NativeUtils.loadLibraryFromJar();
         } catch (java.io.IOException e) {
             e.printStackTrace();
         }
     }}